title: Genie's Blog # your site title
author: yeGenieee
email: cyj95428@gmail.com # email for form submission, you also have to change it in _js/scripts.js
description: > # this means to ignore newlines until "baseurl:"
<<<<<<< HEAD
  차근차근 나아가는 개발자
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yeGenieee.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:  # replace with your_twitter_username or comment to remove link from footer
github_username:  yeGenieee # replace with your_github_username or comment to remove link from footer
instagram_username:  # replace with your_instagram_username or comment to remove link from footer
=======
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://janczizikow.github.io/sleek" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jan_czizikow # replace with your_twitter_username or comment to remove link from footer
github_username:  janczizikow # replace with your_github_username or comment to remove link from footer
instagram_username: shanlongjj # replace with your_instagram_username or comment to remove link from footer
>>>>>>> fd492ecd0b32bda8cc1312cb0b419030afba5d3b
social:
  name: YejinChoi
  links:
    - https://github.com/yeGenieee

disqus:
  shortname: yejchoi # to enable comments replace with your_disqus_shortname

# Build settings
markdown: kramdown
highlighter: rouge # or pygments or null
theme: jekyll-sleek
exclude:
  - README.md
  - node_modules
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.png

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
