title: YeGenie Blog
author: YejinChoi
email:  # email for form submission, you also have to change it in _js/scripts.js
description: "#Developer"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://yejinchoi.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  YejinChoi # replace with your_github_username or comment to remove link from footer
social:
  name: YejinChoi
  links:
    - https://github.com/YejinChoi

disqus:
  shortname:  # to enable comments replace with your_disqus_shortname

# Build settings
markdown: kramdown
highlighter: rouge # or pygments or null
theme: jekyll-sleek
exclude:
  - README.md
  - node_modules
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.png

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
